- name: TASK - installing packages
  ansible.builtin.dnf:
    name: [httpd,mod_ssl,firewalld]
    state: present

- name: TASK - copying index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: '0644'
    setype: httpd_sys_content_t

- name: TASK - start and enabling services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - firewalld
    - httpd

- name: TASK - allowing web rules 
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
    offline: true
  loop:
    - http
    - https
