---
- name: Playbook to create logical volumes
  hosts: all
  vars:
    vg_name: research
    lv_name: data
    lv_size: 400
    lv_alt_size: 300
  tasks:
    - name: TASK - Check if volume group exists - else show error
      ansible.builtin.fail:
        msg: "volume group does not exists"
      when: ansible_facts['lvm']['vgs'][vg_name] is not defined

    - name: TASK - Handling Logical Volume 
      block:
        - name: TASK - Creating logical volume of size 400M
          community.general.lvol:
            vg: "{{ vg_name }}"
            lv: "{{ lv_name }}"
            size: "{{ lv_size }}"
            state: present
          register: lv_400
      rescue:
        - name: TASK - Showing Mesage if not enough space on vg
          ansible.builtin.debug:
            msg: "Could not create logical volume of that size"

        - name: TASK - Creating logical volume of size 300M
          community.general.lvol:
            vg: "{{ vg_name }}"
            lv: "{{ lv_name }}"
            size: "{{ lv_alt_size }}"
            state: present
          register: lv_300
      always:
        - name: TASK - Creating filesystem
          community.general.filesystem:
            dev: "/dev/{{ vg_name }}/{{ lv_name }}"
            fstype: ext4
            force: true
          when: ( lv_400 is defined and lv_400.changed ) or ( lv_300 is defined and lv_300.changed )
