---
- name: Playbook to create partition
  hosts: dev
  tasks:
    - name: Creating partition
      block:
        - name: TASK Creating 1500M partition
          community.general.parted:
            device: /dev/vdb
            number: 1
            state: present
            part_type: primary
            part_end: 1500MiB
          register: part_1500
      rescue:

        - name: TASK Creating 800M partition
          community.general.parted:
            device: /dev/vdb
            number: 1
            state: present
            part_type: primary
            part_end: 800MiB
          register: part_800
      always:
        - name: TASK Creating mount point if not present
          ansible.builtin.file:
            state: directory
            path: /part1
            owner: root
            group: root
            mode: '0755'
          when: ( part_1500 is defined and part_1500.changed) or ( part_800 is defined and part_800.changed)

        - name: TASK Creating File-System
          community.general.filesystem:
            dev: /dev/vdb1
            fstype: ext4
            force: true
          when: ( part_1500 is defined and part_1500.changed) or ( part_800 is defined and part_800.changed)
          register: fs_stat

        - name: TASK Mouting partition
          ansible.posix.mount:
            path: /part1
            src: /dev/vdb1
            fstype: ext4
            state: mounted
          when: fs_stat is defined and fs_stat.changed
    - name: Check and display Error if /dev/vdd does not exists
      ansible.builtin.debug:
        msg: "disk does not exists"
      when: ansible_facts['devices']['vdd'] is not defined
        
      
