---
- name: Playbook-1 to create users on dev and test servers
  hosts: dev,test
  vars_files:
    - user_list.yml
    - locker.yml
  tasks:
    - name: TASK - creating devops group
      ansible.builtin.group:
        name: devops
        state: present
    - name: TASK - creating developer users
      ansible.builtin.user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        state: present
        shell: /bin/bash
        password: "{{ PW_developer | password_hash('sha512') }}"
        groups: devops
        append: true
      when: item.type == "developer"
      loop: "{{ myusers }}"


- name: Playbook-2 to create users on prod servers
  hosts: prod
  vars_files:
    - user_list.yml
    - locker.yml
  tasks:
    - name: TASK - creating opsmgr group
      ansible.builtin.group:
        name: opsmgr
        state: present
    - name: TASK - creating developer users
      ansible.builtin.user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        state: present
        shell: /bin/bash
        password: "{{ PW_manager | password_hash('sha512') }}"
        groups: opsmgr
        append: true
      when: item.type == "manager"
      loop: "{{ myusers }}"


