---
- name: Playbook to manage webcontent
  hosts: dev
  tasks:
    - name: TASK - Creating webdev group if not exists
      ansible.builtin.group:
        name: webdev
        state: present
    - name: TASK - Install required packages if not installed
      ansible.builtin.dnf:
        name: [httpd,mod_ssl,firewalld]
        state: present
    - name: TASK - Creating webdev directory
      ansible.builtin.file:
        state: directory
        path: /webdev
        mode: '2775'
        owner: apache
        group: webdev
        setype: httpd_sys_content_t
    - name: TASK - Creating index.html
      ansible.builtin.copy:
        content: Development
        dest: /webdev/index.html
        owner: apache
        mode: '0644'
        setype: httpd_sys_content_t
    - name: TASK - Creating symlink to the /webdev
      ansible.builtin.file:
        src: /webdev
        dest: /var/www/html/webdev
        state: link
        owner: apache
    - name: TASK - Start and enabled services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - firewalld
        - httpd
    - name: TASK - allowing web services to firewall
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
        offline: true
      loop:
        - http
        - https

